services:
  api: &main_app
    image: ${IMAGE_URI}
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.product_catalog.rule=Host(`${PRODUCT_CATALOG_TRAEFIK_HOST:-product_catalog.localhost}`) || PathPrefix(`/product-catalog`)
      - traefik.http.routers.product_catalog.entrypoints=web
      - traefik.http.routers.product_catalog.service=product_catalog
      - traefik.http.services.product_catalog.loadbalancer.server.port=${PRODUCT_CATALOG_PORT:-8000}
      - traefik.http.middlewares.product_catalog_strip.stripPrefix.prefixes=/product-catalog
      - traefik.http.routers.product_catalog.middlewares=product_catalog_strip
    networks:
      - traefik-shared
    depends_on:
      db:
        condition: service_healthy
    environment:
      PRODUCT_CATALOG_HOST: 0.0.0.0
      PRODUCT_CATALOG_DB_HOST: product-catalog-db
      PRODUCT_CATALOG_DB_PORT: 5432
      PRODUCT_CATALOG_DB_USER: product_catalog
      PRODUCT_CATALOG_DB_PASS: product_catalog
      PRODUCT_CATALOG_DB_BASE: product_catalog
      API_PATH_PREFIX: /product-catalog

  db:
    image: postgres:16.3-bullseye
    hostname: product-catalog-db
    environment:
      POSTGRES_PASSWORD: "product_catalog"
      POSTGRES_USER: "product_catalog"
      POSTGRES_DB: "product_catalog"
    networks:
      - traefik-shared
    volumes:
      - product-catalog-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U product_catalog
      interval: 2s
      timeout: 3s
      retries: 40

  migrator:
    image: ${IMAGE_URI}
    restart: "no"
    command: alembic upgrade heads
    networks:
      - traefik-shared
    environment:
      PRODUCT_CATALOG_DB_HOST: product-catalog-db
      PRODUCT_CATALOG_DB_PORT: 5432
      PRODUCT_CATALOG_DB_USER: product_catalog
      PRODUCT_CATALOG_DB_PASS: product_catalog
      PRODUCT_CATALOG_DB_BASE: product_catalog
    depends_on:
      db:
        condition: service_healthy

volumes:
  product-catalog-db-data:
    name: product-catalog-db-data

networks:
  traefik-shared:
    external: true