"""test_migration.

Revision ID: a0650723be8a
Revises: 7c17db873022
Create Date: 2025-04-07 08:50:31.140548

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "a0650723be8a"
down_revision: Union[str, None] = "7c17db873022"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
