"""create_products_table.

Revision ID: c474009ed81e
Revises: a0650723be8a
Create Date: 2025-04-07 08:55:53.423301

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "c474009ed81e"
down_revision: Union[str, None] = "a0650723be8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
