"""Test migration.

Revision ID: 7c17db873022
Revises: cbe1c34364ed
Create Date: 2025-04-07 07:05:35.187280

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "7c17db873022"
down_revision: Union[str, None] = "cbe1c34364ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
