"""create_products_tables.

Revision ID: 539a9b2ab4f0
Revises: c474009ed81e
Create Date: 2025-04-07 08:56:56.691016

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "539a9b2ab4f0"
down_revision: Union[str, None] = "c474009ed81e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
